docsPath: ./docs
distPath: ./sitedist

config:
 siteMetadata:
   title: okidoc
 pathPrefix: /okidoc
 githubLink: https://github.com/wix/okidoc

codeExamples:
 path: ./examples
 html: <div id="content"></div>
 externalScripts: ['https://unpkg.com/playable@1.10.2/dist/statics/playable.bundle.min.js']

navigation:
  - path: /
    title: okidoc
